---
- name: Install kubernetes python module
  become: yes
  pip:
    name: kubernetes
    state: latest

- name: Install Calico
  block:
    - name: Download Tigera Operator
      get_url:
        url: "https://docs.projectcalico.org/manifests/tigera-operator.yaml"
        dest: "{{ ansible_env.HOME }}/tigera-operator.yaml"

    - name: Create Tigera Operator
      kubernetes.core.k8s:
        state: present
        src: "{{ ansible_env.HOME }}/tigera-operator.yaml"

    - name: Download Custom Resource Definitions
      get_url:
        url: "https://docs.projectcalico.org/manifests/custom-resources.yaml"
        dest: "{{ ansible_env.HOME }}/calico-custom-resources.yaml"

    - name: Insert Pod CIDR in Calico Custom Resources
      lineinfile:
        path: "{{ ansible_env.HOME }}/calico-custom-resources.yaml"
        regexp: '^(.*cidr:).*'
        backrefs: yes
        line: '\1 10.10.0.0/16'
        state: present

    - name: Apply Calico Custom Resources
      kubernetes.core.k8s:
        state: present
        src: "{{ ansible_env.HOME }}/calico-custom-resources.yaml"

    - name: Wait for pods to come up
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: calico-system
        wait: yes
        wait_sleep: 1
        field_selectors:
          - status.phase=Running

    #- name: Remove taint from master node
      #command: kubectl taint nodes --all node-role.kubernetes.io/master-

    - name: Download Calicoctl
      become: yes
      get_url:
        url: "https://github.com/projectcalico/calicoctl/releases/download/v3.19.1/calicoctl"
        dest: "/usr/local/bin/kubectl-calico"
        mode: 755

  environment:
    KUBECONFIG: "~/.kube/config"
    DATASTORE_TYPE: "kubernetes"
