---
- name: Download Helm
  get_url:
    url: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
    dest: '/tmp'

- name: Install Helm
  become: yes
  unarchive:
    src: '/tmp/helm-v3.2.1-linux-amd64.tar.gz'
    dest: /usr/local/bin
    include: linux-amd64/helm
    extra_opts: [--strip-components=1]
    remote_src: yes

